### ISSUE TITLE
include `TTFB` in `CWV` RUM data

### ISSUE THREAD

**Issue by davidnuescheler** [adobe/helix-rum-js#102]
i think it would be great to also include `TTFB` in our RUM data which is helpful when comparing differences of lab data vs. field data.

**Comment by chicharr** [comment]
PRs are open:
https://github.com/adobe/helix-rum-enhancer/pull/79
https://github.com/adobe/helix-rum-js/pull/107

**Comment by chicharr** [comment]
PRs have been merged
