### ISSUE TITLE
include API calls for `.plain.html` and `.json`

### ISSUE THREAD

**Issue by davidnuescheler** [adobe/helix-rum-js#103]
to get a good picture it would be great to include requests to `.plain.html` and `.json` to get a good overview over important resource usage and timing.

**Comment by chicharr** [comment]
We could wrap `window.fetch` with a Proxy and track a checkpoint when fetch requests to `plain.html` or `.json` are executed.
@trieloff do you have another idea?

**Comment by chicharr** [comment]
@Buuhuu this sounds like a good ffetch extension

**Comment by davidnuescheler** [comment]
i really don't like the fetch wrapping extension... i really don't like it when martech does it. also it is unlikely that we should have an `ffetch` dependency in RUM collection.

**Comment by davidnuescheler** [comment]
i should have been more specific... i was thinking of https://developer.mozilla.org/en-US/docs/Web/API/PerformanceEntry/entryType#resource

**Comment by chicharr** [comment]
Hi @davidnuescheler ,
[PR](https://github.com/adobe/helix-rum-enhancer/pull/83) is ready.
Please note, that this will not track the "soft navigations" you implemented as that feature requests the "normal" target path, and not the `.plain.html`

**Comment by chicharr** [comment]
Implemented for `blog.adobe.com` in the `rum-enhancer`.
Currently evaluating if should be extended to other customers
