### ISSUE TITLE
Track aggregated CWV

### ISSUE THREAD

**Issue by chicharr** [adobe/helix-rum-js#105]
**Is your feature request related to a problem? Please describe.**
Keep in the browser's session storage the cwv of the pages visited by the visitor in the current session. The information will be sent to the RUM service only when the page view is part of the sample.

We should keep the average value of each CWV metric.

**Comment by chicharr** [comment]
Code ready in https://github.com/chicharr/helix-rum-enhancer/tree/aggregatedcwv 
To be discussed how this fits in the new miniRUM approach

**Comment by trieloff** [comment]
We should not do this due to the storage requirement
