### ISSUE TITLE
id collisions

### ISSUE THREAD

**Issue by maxakuru** [adobe/helix-rum-js#121]
the current ID generation results in 1-2 character strings, ultimately leading to collisions
since web crypto has good support, maybe we can switch to using builtins for generating uuids, with a simple polyfill fallback

**Comment by trieloff** [comment]
Collisions are ultimately acceptable, as long as the collision rate within a single day for a single site is less than one percent. Even though the IDs are completely random and not persisted in the browser, we don't want to give the impression that they could hide PII, so the shorter the better.

**Comment by davidnuescheler** [comment]
i think that's great, i haven't thought about it that way. i would find it more intuitive (and consistent) if the id was a fixed (albeit short) length, i am thinking 4-6 characters. thoughts?

**Comment by trieloff** [comment]
Fixed length would be an improvement
