### ISSUE TITLE
Id generation logic generates very short id

### ISSUE THREAD

**Issue by kptdobe** [adobe/helix-rum-js#128]
The id generation logic easily generates one or 2 characters length id... I am not sure how important is uniqueness but collisions can every easily happen.

<img width="1102" alt="image" src="https://github.com/adobe/helix-rum-js/assets/474200/5da5342b-9db5-4797-bfcb-4d1efbe1bc2c">

**Comment by trieloff** [comment]
This is working as intended. We intentionally accept some collisions to reduce entropy and preserve privacy.
