### ISSUE TITLE
Error source/target are not reliably captured

### ISSUE THREAD

**Issue by shsteimer** [adobe/helix-rum-js#149]
### Expected Behaviour

When an error occurs, the source and target should always be captured

### Actual Behaviour

In chrome, the source/target are undefined

### Reproduce Scenario (including but not limited to)

go to https://experienceleague.adobe.com/en/docs/experience-manager-cloud-service/content/operations/replication?rum=on

and compare the console output for the error checkpoint in chrome and safari. in chrome, no source/target are defined.

#### Sample Code that illustrates the problem

https://github.com/adobe/aem-lib/blob/main/src/setup.js#L46

The structure of the `event.reason` appears to differ accross browsers, and does not contain a `sourceUrl` or `line` property in Chrome (I have to assume this did at one point work but perhaps was changed in the browser, but haven't investigated that).

**Comment by trieloff** [comment]
I've seen this work consistently in Chrome, but not in Safari, so it's odd that you are reporting the issue for Chrome.

**Comment by shsteimer** [comment]
interesting. Makes me wonder if something about the specific type error that was occurring that led to this case then. I'll try to dig deeper when I get time to see what I can figure out and update here with anything relevant.

**Comment by shsteimer** [comment]
@trieloff 

I created https://errors--franklin-playground--shsteimer.hlx.page to be a minimal example of the various types of errors and how they manifest in rum source/target. Relevant bit of code is at https://github.com/shsteimer/franklin-playground/blob/errors/scripts/scripts.js#L132-L147

| URL  | Chrome v123.0.6312.124 | Safari v17.4 |
| ------------- | ------------- | ------------- |
|   https://errors--franklin-playground--shsteimer.hlx.page/?error=undef&rum=on | `source`:  `` `target`:  ``  | `source`:  `https://errors--franklin-playground--shsteimer.hlx.page/scripts/scripts.js` `target`:  `136`  |
| https://errors--franklin-playground--shsteimer.hlx.page/?error=promise&rum=on  | `source`:  `` `target`:  ``  |`source`:  `https://errors--franklin-playground--shsteimer.hlx.page/scripts/scripts.js` `target`:  `145`  |
| https://errors--franklin-playground--shsteimer.hlx.page/?error=throw&rum=on  | `source`:  `` `target`:  ``  |`source`:  `https://errors--franklin-playground--shsteimer.hlx.page/scripts/scripts.js` `target`:  `141`  |

If there are other types/sources of errors you can think of, let me know and I can add those as well, but at least so far, it seems to be consistently generated in Safari but not in Chrome.

**Comment by trieloff** [comment]
fixed in https://github.com/adobe/aem-lib/pull/65
