### ISSUE TITLE
CSP for websites implemented with Adobe Edge Delivery Services

### ISSUE THREAD

**Issue by AlKaliada** [adobe/helix-rum-js#179]
## Overview
How to implement CSP for  websites implemented with Adobe Edge Delivery Services

## Details
Is any way to add directives to CSP that used nonce attribute to not block RUM script
<script type="module">
            window.RUM_BASE = '/';
            import {sampleRUM} from '/.rum/@adobe/helix-rum-js@^1/src/index.js';
            window.hlx = window.hlx || {};
            window.hlx.sampleRUM = sampleRUM;
            sampleRUM('top');
            window.addEventListener('load', ()=>sampleRUM('load'));
            document.addEventListener('click', ()=>sampleRUM('click'));
</script>

## Proposed Actions
and now?

**Comment by cziegeler** [comment]
The above quoted script block looks like the block injected currently by AEM as a Cloud Service. That injection mechanism is changing soon to a simple script tag with a src attribute - in which case CSP can be configured to allow that script to be loaded.

**Comment by kptdobe** [comment]
@AlKaliada I assume the question has been answer. Feel free to open a new question if needed.
